version: '3'
services:
  flaskapp:
    build: ./flaskapp-docker
    container_name: flaskapp
    #ports:
    #- "8000:8000"
    #network_mode: host

  nginx:
   build: ./nginx
   container_name: nginx
   environment:
     - SERVER_NAME=44.211.174.216
   ports:
     - "80:80"
   restart: always
   #network_mode: host

networks:
  default:
    driver: bridge
